apiVersion: v1
kind: Config
clusters:
- name: tuxin-coreos-cluster
  cluster:
    certificate-authority: /etc/kubernetes/ssl/ca.pem
    server: https://coreos-2.tux-in.com:443
users:
- name: kubelet
  user:
    client-certificate: /etc/kubernetes/ssl/worker.pem
    client-key: /etc/kubernetes/ssl/worker-key.pem
contexts:
- context:
    cluster: tuxin-coreos-cluster
    user: kubelet
  name: kubelet-context
current-context: kubelet-context

