apiVersion: v1
kind: Namespace
metadata:
  name: nginx-ingress

---

apiVersion: v1
data:
  proxy-connect-timeout: "15"
  proxy-read-timeout: "600"
  proxy-send-imeout: "600"
  hsts-include-subdomains: "false"
  proxy-body-size: "1064m"
  server-name-hash-bucket-size: "256"
  use-http2: "true"
  use-gzip: "true"
kind: ConfigMap
metadata:
  namespace: nginx-ingress
  name: nginx

---

apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: nginx
  namespace: nginx-ingress
  labels:
    k8s-app: nginx-ingress-lb
spec:
  template:
    metadata:
      labels:
        name: nginx
        k8s-app: nginx-ingress-lb
    spec:
      containers:
      - image: quay.io/promaethius/ingress
        name: nginx
        imagePullPolicy: Always
        env:
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
        readinessProbe:
          httpGet:
            path: /healthz
            port: 10254
            scheme: HTTP
        livenessProbe:
          httpGet:
            path: /healthz
            port: 10254
            scheme: HTTP
          initialDelaySeconds: 10
          timeoutSeconds: 1
        ports:
        - name: http
          protocol: TCP
          containerPort: 80
          hostPort: 80
        - name: https
          protocol: TCP
          containerPort: 443
          hostPort: 443
        args:
        - /nginx-ingress-controller
        - --default-backend-service=$(POD_NAMESPACE)/default-http-backend
        - --configmap=$(POD_NAMESPACE)/nginx-load-balancer-conf
      nodeSelector:
        ingress: "true"
      hostNetwork: true
